apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: acralpha.azurecr.io/testapp:v1
        ports:
        - containerPort: 100
      imagePullSecrets:
      - name: acr-secret-testapp
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  ports:
  - port: 100
  selector:
    app: testapp
---
apiVersion: v1
kind: Service
metadata:
  name: testapplb
spec:
  type: LoadBalancer
  ports:
  - port: 100
  selector:
    app: testapp